### ISSUE TITLE
Create a minimalistic layout for the QR-CODE-Generator

### ISSUE THREAD

**Issue by BennyPerumalla** [BennyPerumalla/QR-CODE-API#1]
`qr_code_generator.js` make changes in this code, Show a reference layout (Screenshots) before asking for assigning the issue

**Comment by irshadsiddi** [comment]
@BennyPerumalla, I want to work on this issue. Please assign it to me.

**Comment by BennyPerumalla** [comment]
@irshadsiddi Assigned it to you. good luck

**Comment by BennyPerumalla** [comment]
#2 @irshadsiddi
